### ISSUE TITLE
Encoding problem?

### ISSUE THREAD

**Issue by ulvido** [maxcountryman/tower-sessions-stores#20]
store works very fine but I wanted to investigave it with Redis Insight and saw this wierd encoding. Is this intentional or is there a way to fix it? thank you.
![image](https://github.com/maxcountryman/tower-sessions-stores/assets/27722274/384bb6ef-8ecc-4b77-b7a3-71b8276a9e95)

**Comment by maxcountryman** [comment]
[It's encoded with Rust MsgPack](https://github.com/maxcountryman/tower-sessions/discussions/190#discussioncomment-9029423).
