### ISSUE TITLE
`tower_sessions_redis_store`: Reexport TLS features

### ISSUE THREAD

**Issue by jbeaurivage** [maxcountryman/tower-sessions-stores#23]
`tower_sessions_redis_store` reexports the `fred` crate, which helps when creating a `RedisPool`. However, when trying to connect to a cluster using TLS, `fred` expects one of the TLS features to be enabled (one of `enable-native-tls`, `enable-rustls` or `enable-rustls-ring`).

Without one of those features, `fred` will not connect to the cluster, and return an error instead.

## Workaround

Currently, a workaround is for the user to pull in the `fred` crate with one of the TLS features enabled. However, this requires them to have to keep the `fred` version in sync with the version `tower_sessions_redis_store` depends on, which may lead to unexpected runtime errors when crates are updated.

## Proposed fix

Reexport the TLS features from `fred` in `tower_sessions_redis_store`, so that the user may enable one of them without having to depend on `fred` directly.

**Comment by maxcountryman** [comment]
Your proposed fix is to add a feature flag to the store crate, correct?

Isn't it more flexible to allow specifying fred features directly instead of having to manually map them to store crate features?

**Comment by jbeaurivage** [comment]
Yes, that's correct. Depending directly on fred to specify features is probably more flexible indeed, but I think the main problem is that if I, as a user, pull in e.g. fred version 9.0.3 specifically to enable a TLS feature, while tower_sessions_redis_store depends on fred 8.0.6, there will be no compile error, albeit maybe an unused dependency (if I use the reexported fred types from tower_sessions_redis_store).

The problem is if I decide to upgrade fred to the latest version while tower_sessions_redis_store still depends on  an older version (because I forgot about that quirk), the discrepancy will not manifest itself at compile time, but at runtime only if connecting to a TLS-enabled cluster.

I suppose a better workaround could be not to use the reexported fred types from tower_sessions_redis_store so that a version mismatch will give a compile error. It's really not a big problem, I just figured I could bring it to your attention and maybe help others that might run into this issue too.

**Comment by maxcountryman** [comment]
Thanks for mentioning this. I don't feel strongly so if you think it would help (it does sound preferable to have a compile time error) I'm happy to look at a PR.
